### ISSUE TITLE
Running `npx elegant-init` not doing anything!

### ISSUE THREAD

**Issue by douglasrcjames** [elegantframework/elegant-cli#12]
Hi,

I am trying to setup this CMS on my PC, but the command `npx elegant-init` doesn't do anything in terminal, just starts a new session or something, but I do not see anything created.

**Comment by Bowens20832** [comment]
Hey @douglasrcjames, thank you for supporting Elegant! 

The `npx elegant-init` command copies over the Elegant project and configures it for you in the directory where you ran the init command.

![Screenshot 2023-04-18 071600](https://user-images.githubusercontent.com/10189130/232760772-40e86702-2d23-47aa-96ea-c454ab9da9c7.png)

The next steps would be to simply run `npm install` to install the required dependencies, and then `npm run dev` to start the project locally at localhost:3000.

**Comment by Bowens20832** [comment]
Hey @douglasrcjames I am about to start addressing this with a fix in the next release. 

Do you have anymore thoughts on this topic before I fix and close this issue?

**Comment by Bowens20832** [comment]
This issue has been addressed and resolved in Elegant v2.1 .. You can demo the updates by installing our release candidate `npm install  elegant-cli@2.1.1-prerelease.5`

https://www.npmjs.com/package/elegant-cli/v/2.1.1-prerelease.5
