### ISSUE TITLE
Upgrade Next.js to version 13.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#123]
I would like to simply bump the current version of Next.js to the latest version.

I don't want to do anything related to the new server vs. client components.

The scope of this ticket will be to only upgrade to version 13, so that all of our dependencies are up to date.

_Originally posted by @Bowens20832 in https://github.com/elegantframework/elegant-cli/discussions/112_

**Comment by Bowens20832** [comment]
- [x] Update Next.js to version 13.
- [x] Verify all tests are passing.

**Comment by juanmanzanero-com** [comment]
Do you want to keep using the pages router or do you want to upgrade to the new app router? 🤔

**Comment by Bowens20832** [comment]
> Do you want to keep using the pages router or do you want to upgrade to the new app router? 🤔

Hey @juancmandev, I hadn't made a decision either way and left it open to feedback. 

Next 13 and the pages/app have been a hot-button topic lately, so I don't have an opinion either way.

I was considering just upgrading to Next 13 while continuing to use the pages.. What are your thoughts?

**Comment by juanmanzanero-com** [comment]
I'd used both approaches.

App router is focused to be more productive and type less code, using more intuitive functions to handle metatags easily and create server functions to send the HTML with data to the client to improve SEO and performance.

Is really neccesary? If you want to get the best UX then server components is the best approach for the user and web crawlers. You can still achieving all that with the pages router , app router is just a more productive way to achieve that saving you typing so much code.

We can combine both approaches too, using app router for new features and eventually migrate pages router.

I could help to migrate, I just need to use your project and see if is really necessary and check where the app could be improved

**Comment by Bowens20832** [comment]
I am currently in progress on this issue, but I am blocked due to a bug between Next.js 13.4, Tailwind's UI packages, and Jest.

https://github.com/vercel/next.js/pull/54206#issuecomment-1694403206

Stand by for updates from them.

**Comment by Bowens20832** [comment]
Complete 😃

**Comment by Bowens20832** [comment]
Resolved by #163
