### ISSUE TITLE
The Steps component should render properly on the Deployment docs page.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#143]
**Describe the bug**
Rehype does not seem to processing the React statements on the Deployment docs page.

**To Reproduce**
1. Go to http://localhost:3000/docs/deployment
2. Compare to the live site for reference: https://www.elegantframework.com/docs/deployment

**Expected behavior**
Display the Steps(1, 2, 3, 4) component on the docs pages.

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/c1955739-42c2-4ef2-ad1e-b5a3fe267a24)

**Screenshots**
![image](https://github.com/elegantframework/elegant-cli/assets/10189130/9aed94d4-6817-4249-8d71-0ef3eb5913ad)

**Comment by ValkonX33** [comment]
Hey can you elaborate how it should look like for better understanding ?

**Comment by Bowens20832** [comment]
> Hey can you elaborate how it should look like for better understanding ?

Rehype should process the markdown, and load the <Steps /> React component.

Probably just need to add the RehypeReact lib to MarkdownToHtml.ts 

source\elegant\src\utils\core\Rehype\MarkdownToHtml.ts
