### ISSUE TITLE
Remove lower level header items from the Table of Contents component.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#147]
**Describe the bug**
The Table of Contents on the docs pages is displaying the lower level headings.

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/a2f7acc4-927a-404a-a861-494af72c56f4)

**Comment by ratishjain12** [comment]
@Bowens20832 can you please elaborate this issue so that I can fix it properly

**Comment by Bowens20832** [comment]
> @Bowens20832 can you please elaborate this issue so that I can fix it properly

Hey @ratishjain12, thank you for commenting 😄 

The h5 and h6 tags should not be showing in the table of contents, and can be ignored by Rehype

The expected outcome would look like the screenshot from below:

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/e0392904-2a6c-492d-9cf3-685e2a464c8b)

**Comment by ratishjain12** [comment]
Assign it to me I can work on this

**Comment by ratishjain12** [comment]
u mean that likelihood of impact one right?
that should be removed?

coz in table of contents its already looking like what you have shown

**Comment by Bowens20832** [comment]
> u mean that likelihood of impact one right? that should be removed?
> 
> coz in table of contents its already looking like what you have shown

When you go to localhost:3000/docs/upgrade you will see that the table of contents has added the "Likelihood of Impact:" h5 tags.

**Comment by ratishjain12** [comment]
yeah below updating dependencies right?

**Comment by Bowens20832** [comment]
> yeah below updating dependencies right?

No, I believe you just need to pass which heading types to include or exclude in this options object in RehypeToc.ts file.

source\elegant\src\utils\core\Rehype\RehypeToc.ts

**Comment by ratishjain12** [comment]
Gotcha

**Comment by Bowens20832** [comment]
Resolved by #177 

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/9bcc194d-d837-48e3-bd23-7cf7872009dd)
