### ISSUE TITLE
The active link on the documentation sidebar is broken when a url query string is included the url. 

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#197]
The active link on the documentation sidebar is broken when a url query string is included the URL. 

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/55499dbf-9c9e-45c1-8e64-500e827af1aa)

**Comment by JonathanRech** [comment]
Hello @Bowens20832 I woud like to work on this issue if possible.

**Comment by Tashuuuu** [comment]
Can I work on it?

**Comment by Bowens20832** [comment]
> Can I work on it?

Assigned it to you.. Thanks for the help 😄

**Comment by Bowens20832** [comment]
Resolved by #239.

Thanks for the help @Tashuuuu
