### ISSUE TITLE
Add a link to the "Getting Started with Elegant CMS" guide to the bottom of the Admin landing page.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#200]
Add a url link to the "configuring authentication" section of the getting started page to the bottom of the card that is displayed when a user navigates to /admin for the first time.

https://www.elegantframework.com/docs/getting-started-with-elegant-cms#configuring-authentication

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/a4a1819c-f395-4ca9-b53e-ef1d4f12134d)

**Comment by wrth1337** [comment]
Hi @Bowens20832. I'd like to work on this issue :)

**Comment by wrth1337** [comment]
When I access the admin page I get a 404. Is this intended?

**Comment by Bowens20832** [comment]
> When I access the admin page I get a 404. Is this intended?

No. My apologies for that.. The admin panel is included in version 3.0.

Version 3.0 is in prerelease currently, and you can download it with the following: ```npm i elegant-cli@3.0.1-prerelease.1```
