### ISSUE TITLE
The card on the admin login page should be "bg-white" in dark mode.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#202]
In the screenshot below, the html elements on the card displayed on the admin login page are not displaying properly in dark mode.

Fix in the welcome.tsx file.

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/f8b45d5f-635f-4b81-9e85-87a1127d67ca)

Spotted by @wrth1337 in #201

**Comment by wrth1337** [comment]
I can work on this issue.

**Comment by Bowens20832** [comment]
> I can work on this issue.

Awesome! I just assigned it to you 😎 

Thank you for the help!

**Comment by Bowens20832** [comment]
Resolved @wrth1337 .. Thank you for the help though 😄 

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/87b1775c-25f5-4320-9397-289b2cfe1fee)
