### ISSUE TITLE
Table of Contents breaks the app when no heading element has been included in a page.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#210]
**Describe the bug**
If you don't add an H1 or H2 element in the content editor, the table of contents on the frontend will break during page load.

**To Reproduce**
1. Create a new document.
2. Do not add any heading items
3. Go to the page on the frontend

**Screenshots**
![image](https://github.com/elegantframework/elegant-cli/assets/10189130/f8a49547-3cbb-44c9-9c60-30cd28f1fb74)

**Comment by Pooja1672** [comment]
Hi @Bowens20832 , I would like to work on this issue. Can you please assign it to me?

**Comment by Bowens20832** [comment]
> Hi @Bowens20832 , I would like to work on this issue. Can you please assign it to me?

Thank you @Pooja1672 for your interest in this ticket. I will go ahead and assign it to you. 

Ask me any questions if you need, or jump in our Discord chat 😄
