### ISSUE TITLE
The "Sign out" button in the CMS admin panel is not clickable.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#234]
**Describe the bug**
The signout button in the CMS admin panel is not clickable, and therefore users can't log out of their accounts.

**To Reproduce**
1. Log into the admin panel. /admin
2. Click the users image on the right hand side.
3. Click signout in the dropdown.

**How to fix**
- Increase the Z-index of the dropdown and/or header.
- Reduce the z-index of the main content container?

**Expected behavior**
Click the users image on the right hand side of the admin, and click signout in the dropdown.

The user should be logged out of the admin panel.

**Screenshots**

![Screenshot 2023-12-06 121045](https://github.com/elegantframework/elegant-cli/assets/10189130/cc1ef372-b218-49d5-a723-1207cbffecd2)

**Comment by ghost** [comment]
i dont how to deploy this on verlce can someone help me

**Comment by Bowens20832** [comment]
> i dont how to deploy this on verlce can someone help me

Hey @8vish, deploying to Vercel is super easy and can be done in just a few minutes.

Here is a detailed guide on deploying to Vercel: [https://www.elegantframework.com/docs/deployment#creating--deploying-your-application](https://www.elegantframework.com/docs/deployment#creating--deploying-your-application)

Please let me know if you need any more assistance! 🙇‍♂️

**Comment by ghost** [comment]
> > i dont how to deploy this on verlce can someone help me
> 
> Hey @8vish, deploying to Vercel is super easy and can be done in just a few minutes.
> 
> Here is a detailed guide on deploying to Vercel: https://www.elegantframework.com/docs/deployment#creating--deploying-your-application
> 
> Please let me know if you need any more assistance! 🙇‍♂️



i got this error when i fork your repo and deploy on vercle plese help me
![Screenshot 2023-12-08 193018](https://github.com/elegantframework/elegant-cli/assets/139675851/ff7f24b8-73e1-4117-924f-40131447a381)

**Comment by ghost** [comment]
sorry but i am so dumb i since 2 days i tried to deploy on cloud or local matchine but i can when i make commond to install on my local matching so show install but files are not come in folder

**Comment by ghost** [comment]
![Screenshot 2023-12-08 220701](https://github.com/elegantframework/elegant-cli/assets/139675851/6cc9801c-d796-45ea-a4be-57504ec1bc59)

**Comment by Bowens20832** [comment]
> ![Screenshot 2023-12-08 220701](https://private-user-images.githubusercontent.com/139675851/289133187-6cc9801c-d796-45ea-a4be-57504ec1bc59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTMxODIsIm5iZiI6MTcwMjA5Mjg4MiwicGF0aCI6Ii8xMzk2NzU4NTEvMjg5MTMzMTg3LTZjYzk4MDFjLWQ3OTYtNDVlYS1hNGJlLTU3NTA0ZWMxYmM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwMzM0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWQyY2ZlZGUyNjQwMTk1ZjZkMDNmYTUyODI0ZWMyNTA1OTYxYjk3YjY0Zjg0MWE1ODA0ZGEwYjE1YzcwZmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tDdMni3Di9nB03p3jykaWm65hp9Eh6aRXsd6jvmChx8)

You're so close! 

Just set your environment variables inside of the project settings, and it should work 😃 

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/a7dac787-0fb6-42ab-bbab-3b01a25df643)

**Comment by Bowens20832** [comment]
> ![Screenshot 2023-12-08 220701](https://private-user-images.githubusercontent.com/139675851/289133187-6cc9801c-d796-45ea-a4be-57504ec1bc59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTM1MjAsIm5iZiI6MTcwMjA5MzIyMCwicGF0aCI6Ii8xMzk2NzU4NTEvMjg5MTMzMTg3LTZjYzk4MDFjLWQ3OTYtNDVlYS1hNGJlLTU3NTA0ZWMxYmM1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwMzQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmI2ZTcyMzMxYWI2YzlmYWE0NzAyNjEwYzBkMjQwNzc0ODcxMGVjY2JjN2M5ZTkyNGI1ZDJiOTlmNGY3NTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XGCu1tIA0gBvXFicX1Gn8m-OfzQsavF5ZvB9q3W3Or4)

If you need any help, feel free to message me on Discord or WhatsApp!

[Elegant on Discord](https://discord.gg/PwY38x4uvV)

![MicrosoftTeams-image](https://github.com/elegantframework/elegant-cli/assets/10189130/a00dba41-5ce9-45b1-a27e-19b1c2162019)
