### ISSUE TITLE
A project with no .env variables set will break during build.. Fix this

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#235]
A project that has no .env variables set will break during the build step, thus causing user confusing and friction.

Fix this by making what ever is calling the toUpperCase() method more graceful.
 
             ![Screenshot 2023-12-08 220701](https://github.com/elegantframework/elegant-cli/assets/139675851/6cc9801c-d796-45ea-a4be-57504ec1bc59)

_Originally posted by @8vish in https://github.com/elegantframework/elegant-cli/issues/234#issuecomment-1847499271_

**Comment by ghost** [comment]
i just update cde via chat gpt so its working use this code

/**
 * Capitalize the first letter of every word in a string.    
 * @param str A normal string.
 * @returns A kebab cased string.
 */
const TextToKebabCase = (str: string) => {
    const words = str.split(" ");

    return words
        .filter((word) => !!word) // Remove undefined or empty strings
        .map((word) => { 
            return word[0].toUpperCase() + word.substring(1); 
        })
        .join(" ");
};

export default TextToKebabCase;
