### ISSUE TITLE
not working new collection

### ISSUE THREAD

**Issue by ghost** [elegantframework/elegant-cli#236]
when i add new collection so in github new folder is not generating for specific collection

**Comment by Bowens20832** [comment]
> when i add new collection so in github new folder is not generating for specific collection

Hey @8vish Thanks for reporting this issue! 😎 

Can you paste a screenshot of the issue here?

**Comment by Bowens20832** [comment]
This has been confirmed not to be an active issue within the Elegant project, and this item has become stale.

As a result, I am closing this ticket for now.

For information on creating new collections using the Elegant CMS package, please visit here: [Collections](https://www.elegantframework.com/docs/creating-collections)

If you find this to still be an issue, or have a similar problem or concern, please open a new bug report on this project 👍
