### ISSUE TITLE
Adding Pagination Feature to Elegant Framework

### ISSUE THREAD

**Issue by ViSurya** [elegantframework/elegant-cli#375]
I switched from WordPress to Elegant Framework for my blog due to WordPress being slow and outdated. However, with over 300+ pages on my site, navigating through them is difficult without pagination. I tried adding pagination using a template from Flowbite documentation, but I couldn't get it to work with Elegant Framework.

**Solution Needed:**
I need help adding pagination to Elegant Framework to make it easier to navigate through my numerous pages. The solution should be easy to implement and blend well with the framework's design.

**Considered Options:**
I've thought about manually adding pagination or seeking help from the community or a developer. However, I prefer a straightforward solution that I can manage myself.

**Additional Info:**
Here's the link to the pagination template I tried: [Flowbite Pagination Component](https://flowbite.com/docs/components/pagination/) Any assistance in integrating pagination into Elegant Framework would be appreciated.

there screenshot of Pagination snippet
![image](https://github.com/elegantframework/elegant-cli/assets/155606627/11013e9f-e80a-4acb-8cc6-e87e6e004b63)

**Comment by Bowens20832** [comment]
> I switched from WordPress to Elegant Framework for my blog due to WordPress being slow and outdated. However, with over 300+ pages on my site, navigating through them is difficult without pagination. I tried adding pagination using a template from Flowbite documentation, but I couldn't get it to work with Elegant Framework.
> 
> **Solution Needed:** I need help adding pagination to Elegant Framework to make it easier to navigate through my numerous pages. The solution should be easy to implement and blend well with the framework's design.
> 
> **Considered Options:** I've thought about manually adding pagination or seeking help from the community or a developer. However, I prefer a straightforward solution that I can manage myself.
> 
> **Additional Info:** Here's the link to the pagination template I tried: [Flowbite Pagination Component](https://flowbite.com/docs/components/pagination/) Any assistance in integrating pagination into Elegant Framework would be appreciated.
> 
> there screenshot of Pagination snippet ![image](https://private-user-images.githubusercontent.com/155606627/306690239-11013e9f-e80a-4acb-8cc6-e87e6e004b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjkwNDIsIm5iZiI6MTcwODU2ODc0MiwicGF0aCI6Ii8xNTU2MDY2MjcvMzA2NjkwMjM5LTExMDEzZTlmLWU4MGEtNGFjYi04Y2M2LWU4N2U2ZTAwNGI2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQwMjI1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzBmZWY1NDkwM2M1OTlhMGRiYTU4Y2I5MDRjYThlN2UwOGYyYWI2MzQ0OGVjMzYxOWVmZTdmYjJlNjAyNWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G28KDUlrbOAMyIY_tGHPrcD4mXux8Hwr5sIjrQ2FPmA)

Hey @ViSurya thanks for opening this feature request!

Adding pagination shouldn't be too challenging, and I'm sure other users of the project would appreciate this feature.

I'll start working on it immediately, and will keep you updated 😄

**Comment by ViSurya** [comment]
Thanks @Bowens20832

**Comment by Bowens20832** [comment]
Hey @ViSurya thank you for opening this feature request! 

We have completed the development on this and it is now readily available is the latest Elegant release; version 3.2.0.

You can demo it live here: [Elegant Demo](https://demo.myelegant.app/blog)

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/5b17d1b4-5d14-4546-a32b-f30857740675)
