### ISSUE TITLE
As a content creator, I would like my web application to include a basic trademark policy page.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#42]

**Comment by Bowens20832** [comment]
As a content creator, I would like my web application to include a basic trademark policy page.

- [ ] Create /legal namespace
- [ ] Create trademark-policy.mdx page
- [ ] Create boiler plate trademark policy using ENV vars.
- [ ] Follow Vercels lead: https://vercel.com/legal/trademark-policy

**Comment by rabisnaqvi** [comment]
hi @Bowens20832 ! could you assign this issue to me? I'll look into this today or tomorrow.

**Comment by Bowens20832** [comment]
Resolved by #44
