### ISSUE TITLE
Setting up a default theme

### ISSUE THREAD

**Issue by hvitis** [elegantframework/elegant-cli#461]
**Describe the solution you'd like**
I would like to know or to have a variable that sets the default theme. Currelty I see that the system theme is being implemented as default, but my website is not prepared for themes yet so I would like to HARDCODE light theme. How would I do that?

**Describe alternatives you've considered**
I was thinking about throwing out all theme settings in tailwind config but I dont want to do that since I will soon move to setting up themes.

**Additional context**
That´s more of a question if it´s possible to set a light theme as default somewhere now?

**Comment by Bowens20832** [comment]
> **Describe the solution you'd like** I would like to know or to have a variable that sets the default theme. Currelty I see that the system theme is being implemented as default, but my website is not prepared for themes yet so I would like to HARDCODE light theme. How would I do that?
> 
> **Describe alternatives you've considered** I was thinking about throwing out all theme settings in tailwind config but I dont want to do that since I will soon move to setting up themes.
> 
> **Additional context** That´s more of a question if it´s possible to set a light theme as default somewhere now?

Hey @hvitis! Thanks for reaching out and opening an issue.

To have the theme default to light, simply remove the `dark` css class in the <html></html> element in src/pages/_document.js  on line 12

https://github.com/elegantframework/elegant-cli/blob/319204bc1916792e8b5539cc107b9a979d946f1c/source/elegant/src/pages/_document.js#L12

**Comment by Bowens20832** [comment]
Hey @hvitis, I hope all is well! 

I have not heard any more feedback on this issue, and it has gone stale. I am closing this issue for now, but feel free to comment or reopen it if you are still having issues.

Thank you again for supporting Elegant 😎
