### ISSUE TITLE
Migrate Elegant to Next 14, and the app router; away from the old pages routing.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#500]
### Discussed in https://github.com/orgs/elegantframework/discussions/499

<div type='discussions-op-text'>

<sup>Originally posted by **Bowens20832** May 21, 2024</sup>
It is time to migrate the existing Elegant application to the new app router.</div>

**Comment by ChristopherAlphonse** [comment]
I would love to help with with this.

**Comment by Bowens20832** [comment]
Hey @ChristopherAlphonse thank you for offering some help! 

We would love some support with the current build. 

I am about 95% with a useable beta for Elegant v4: https://github.com/elegantframework/elegant-cli/tree/v4.x/packages/elegant

What do you think?
