### ISSUE TITLE
As a website owner, I would like to have a security.txt file included in my website.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#58]
As a website owner, I would like to have a security.txt file in the root of my application. This file is similar to the robots.txt file, and will serve as a landing point for security researchers and any other people who may stumble into a security issue.

The security.txt file will hold basic info about how someone may report a security issue.

This topic has come up recently alot online, and is now a requirement of all Dutch government website. Though the Dutch government may be a small market for Elegant currently, we have ambitions of being able to support any user who wish to uses Elegant, even if it is a government entity.

https://netherlands.postsen.com/trends/198695/Securitytxt-now-mandatory-for-Dutch-government-websites.html

This topic was futher encouraged for Elegant by users on Hacker News: https://news.ycombinator.com/item?id=36149004#36152473

- [x] Create a ".well-known" directory under source/elegant/public/.well-known
- [x] Create security.txt file
- [x] Include link to Elegant's pgp key for secure communication.
- [x] Include base app contact info, and/or the contact info of Elegant.

**Comment by Bowens20832** [comment]
Real security.txt file here: https://www.ncsc.nl/.well-known/security.txt
![Screenshot 2023-06-01 224548](https://github.com/elegantframework/elegant-cli/assets/10189130/dd7bd412-5c80-4c58-9ab1-fc532446b5be)

**Comment by Bowens20832** [comment]
gpg --clearsign --default-key security@elegantframework.com security.txt


Contact: mailto:security@elegantframework.com
Expires: 2027-10-24T14:00:00.000Z
Encryption: https://www.elegantframework.com/.well-known/pgp-key.txt
Preferred-Languages: en
Canonical: https://www.elegantframework.com/security.txt

**Comment by Bowens20832** [comment]
> gpg --clearsign --default-key [security@elegantframework.com](mailto:security@elegantframework.com) security.txt
> 
> Contact: [mailto:security@elegantframework.com](mailto:security@elegantframework.com) Expires: 2027-10-24T14:00:00.000Z Encryption: https://www.elegantframework.com/.well-known/pgp-key.txt Preferred-Languages: en Canonical: https://www.elegantframework.com/security.txt

Thanks @SkyBulk

**Comment by SkyBulk** [comment]
You're very welcome! It was my pleasure to contribute to the security initiatives at Elegant Framework. I'm glad I could assist and look forward to our continued collaboration.

**Comment by Bowens20832** [comment]
Resolved by #590
