### ISSUE TITLE
As a developer, I would like the navigation and authors config to be under the '/config' namespace.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#59]
As a developer, I would like the navigation and authors config to be under the '/config' namespace. 

The config namespace serves as the central configuration handler within Elegant. 

- [ ] Create navigation.ts file
- [ ] Create authors type (Optional)
- [ ] Create authors.ts file
- [ ] Delete navs folder

**Comment by Shiv-2712** [comment]
Hi, Bownes
Can I help you with this issue?

**Comment by Bowens20832** [comment]
Hey Shiv,

Yes please! We would love some help 😎

I have a long list of items on my todo list, and elegant seems to be taking off faster than I can tackle each item.

What do you think? Could you tackle this?

It should be a pretty simple item. I intentionally made it an easy item so that other devs in the community could get involved.

Sincerely,

Brandon Owens

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SaxenaShiv** [comment]
I sincerely value your requirement, and I have diligently made multiple attempts to configure the Elegant-Cli tool on my Windows PC. Unfortunately, I have encountered challenges in executing it successfully. However, I am open to exploring alternative solutions, such as utilizing a virtual machine to install macOS. By doing so, I can acquire the necessary environment to provide the assistance you seek. I have also made efforts to run it on Ubuntu but encountered repeated errors regarding a specific missing dependency. Given the complexity of the situation, I humbly request the guidance and support of a mentor to help overcome these obstacles.

**Comment by Bowens20832** [comment]
> I sincerely value your requirement, and I have diligently made multiple attempts to configure the Elegant-Cli tool on my Windows PC. Unfortunately, I have encountered challenges in executing it successfully. However, I am open to exploring alternative solutions, such as utilizing a virtual machine to install macOS. By doing so, I can acquire the necessary environment to provide the assistance you seek. I have also made efforts to run it on Ubuntu but encountered repeated errors regarding a specific missing dependency. Given the complexity of the situation, I humbly request the guidance and support of a mentor to help overcome these obstacles.

Hmmmmmmm 🤔  .

Please don't give up! This whole project strives to make it as simple as possible for any dev to set up a fully loaded website in just a few minutes..

Elegant 100% works on Windows, and should have no issues on Mac using NPM.

Are you using Visual Studio Code?

Is node.js installed on your computer?

Have you followed the [install guide](https://www.elegantframework.com/docs/installation)?

Have you come across the install video on Youtube yet? [How to get started with Elegant - v2.2](https://youtu.be/bS66QUBKljM)

The install video is brand new, and I used it to brushen up on my video skills; and to help me develop around the new Video component coming in the next release. #40 #75

**Comment by Bowens20832** [comment]
@Shiv-2712 Thank you for this effort at least! I am going to document all of this and turn everything I mentioned above into offical docs and how-tos.

Also, I'm starting on the editor because I need about 100 pages of docs and guides explaining every feature of Elegant, but doing that without an editor is cumbersome.

Having the simple content editor soon is going to boost our content by 100x 🚀

**Comment by SaxenaShiv** [comment]
Greetings Mr Bowens,
Thank you for the motivation, I think now I am able to contribute to this project.

**Comment by Bowens20832** [comment]
Hey @Shiv-2712, are you still interested in tackling any of these action items?

Let me know 😄

**Comment by SaxenaShiv** [comment]
Certainly, I have exams at the moment, which means I'll need some time to devote to this task. However, I assure you that I will find a way to handle it. Do you happen to know if there's a Slack group available where we can conveniently communicate?

**Comment by Bowens20832** [comment]
> Certainly, I have exams at the moment, which means I'll need some time to devote to this task. However, I assure you that I will find a way to handle it. Do you happen to know if there's a Slack group available where we can conveniently communicate?

Hey no rush @Shiv-2712, i'll leave this open for you.. Take your time, and good luck on your exams!

**Comment by Bowens20832** [comment]
@Shiv-2712 I set up a Discord chat here: https://discord.com/invite/PwY38x4uvV
