### ISSUE TITLE
As a developer, I need an 'Admin' page layout component for a content creation portal.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#77]
I am actively R&Ding #49, and I have a solution.

The new content creation portal needs a different header that has different nav items for site admin users.

The current header and content portal do not jive.

Removing items and playing with Outstatic really seem to create something 'elegant'.

![MicrosoftTeams-image (12)](https://github.com/elegantframework/elegant-cli/assets/10189130/4f5e1720-62a2-4b23-8061-ffcf1b1f84d5)

- [ ] Create admin page layout.

**Comment by Bowens20832** [comment]
I have been exploring this further. 

I full "Admin" layout may not be needed. We may be able to just use the existing layout props instead.

```
Outstatic.layoutProps = {
    meta: {
        title: MetaTitle(Config('app.name'), Config('app.tagline'))
    },
    stickyHeader: true
};
```

I have also been playing around with the sticky header, and turning the beams background off/on in the admin panel.

![Screenshot 2023-06-13 213356](https://github.com/elegantframework/elegant-cli/assets/10189130/b571d91b-9b4e-4a90-835c-1a7b41f2a084)


![Screenshot 2023-06-13 213540](https://github.com/elegantframework/elegant-cli/assets/10189130/f5beeac3-59e1-4d8c-ab5f-58d197c50eaf)

**Comment by SaxenaShiv** [comment]
I think turning on the beams background is more "elegant"

**Comment by Bowens20832** [comment]
> I think turning on the beams background is more "elegant"

Hey @Shiv-2712 thank you for the feedback! It's greatly appreciated 😄 

I ran it by some other smart minds, and the general consensus is that the beams are going to stay ❤️

**Comment by Bowens20832** [comment]
I have dived further into developing the CMS panel, and this issue is not relevant anymore. 

I am closing this in favor of the innovations made here: https://github.com/elegantframework/elegant-cli/tree/feature%2Foutstanding
