### ISSUE TITLE
As a developer, I would like to add an "arrow" to any external URL's; to signal to users that a url likes to an external website

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#81]
As a developer, I would like to add an "arrow" to any external URL's; to signal to users that a url likes to an external website.

See Vercel's header with external links that open in a new page:

![image](https://github.com/elegantframework/elegant-cli/assets/10189130/70b5e277-fe11-4eb2-8711-50e2f3974240)

**Comment by SaxenaShiv** [comment]
Hello, I'm interested in working on this feature.

**Comment by Bowens20832** [comment]
Awesome @Shiv-2712! Would you like me to assign this item to you?

**Comment by SaxenaShiv** [comment]
Yes, I would like to work on this issue.

**Comment by SaxenaShiv** [comment]
## Please let me know if this meets your expectations by providing feedback.

![image](https://github.com/elegantframework/elegant-cli/assets/74370135/730f0a54-6d2d-45b3-ba45-a3d8333acc15)

**Comment by Bowens20832** [comment]
@Shiv-2712 Yes. those arrow icons are what I was thinking.

However, the arrows should only be visible on URLs marked as "external", and leave the website.

**Comment by SaxenaShiv** [comment]
> @Shiv-2712 Yes. those arrow icons are what I was thinking.
> 
> However, the arrows should only be visible on URLs marked as "external", and leave the website.

I request you to please provide an example in code to indicate the specific sites you desire as external links so that I can make the changes accordingly.

**Comment by Bowens20832** [comment]
The community urls in the footer are linking to external URLs.

source\elegant\src\components\core\Footer\SplashFooter.tsx

![Screenshot 2023-07-02 094033](https://github.com/elegantframework/elegant-cli/assets/10189130/431ca07b-e3b0-4f31-9906-f478158a4cc4)
